<a href="https://colab.research.google.com/github/Pradhan14102003/python-programming/blob/main/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***My First Program***

In [ ]:
print("hello")

hello


***Variable declaration in python***

In [ ]:
a=5
b=9
sum=a+b
print(sum)
print("sum")

14
sum


***Assignment-1***

In [ ]:
import math
a=5
b=13
c=10
d=9
diff=a-b-c
mul=a*b
div=b/a
rem=b%a
sqr=a*a
root=math.sqrt(d)
print("difference between" ,a, b, "and", c,"is",diff)
print("product between" , a, b,"is",mul )
print(b,"divided by",a,"is",div)
print("reminder of 13/5 is",rem)
print("square root of", d, "is",root)

difference between 5 13 and 10 is -18
product between 5 13 is 65
13 divided by 5 is 2.6
reminder of 13/5 is 3
square root of 9 is 3.0


***Data types***

In [ ]:
name2="He & 123"
print(type(name2))

<class 'str'>


In [ ]:
name="Hello"
print(type(name))

<class 'str'>


***Lists***

In [ ]:
lis=['Hello','123','30.23']
type(lis)
print(lis)

['Hello', '123', '30.23']


In [ ]:
lis2=['apple','200','India']
print(len(lis))
print(len(lis2))
lis3=lis+lis2
print(lis3)
lis2.append("Hello")
lis2.clear()
lis=['kk','aa','kle']
lis[0]
lis.sort()

3
3
['kk', 'aa', 'kle', 'apple', '200', 'India']


***Tuples***

In [ ]:
tuple=("Hubli","Belgaum","Hubli")
print(type(tuple1))
tuple2=("Hubli",)
print(type(tuple2))
tuple3=(1,2,3,4,5)
print(type(tuple3))
tuple1=("Hubli","Dharwad","Hubli")
print(tuple[0])
print(tuple[1])
print(tuple[-1])
tuple6=tuple1+tuple1
print(tuple6)
tuple7=tuple6*2
print(tuple7)
y=tuple7.index('Hubli')
print(y)
x=tuple7.count('Dharwad')
print(x)


<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
Hubli
Belgaum
Hubli
('Hubli', 'Dharwad', 'Hubli', 'Hubli', 'Dharwad', 'Hubli')
('Hubli', 'Dharwad', 'Hubli', 'Hubli', 'Dharwad', 'Hubli', 'Hubli', 'Dharwad', 'Hubli', 'Hubli', 'Dharwad', 'Hubli')
0
4


In [ ]:
x=("Hubli","Dharwad","belgaum")
print(type(x))


<class 'tuple'>


In [ ]:
y=list(x)
y[2]='bangalore'
print(y)


['Hubli', 'Dharwad', 'bangalore']


***Sets***

In [ ]:
set1={"Red","Blue","Black"}
print(set1)
set1.add('orange')
print(set1)
set2={"ball","bat","wicket"}
set1.update(set2)
print(set1)

{'Black', 'Blue', 'Red'}
{'orange', 'Black', 'Blue', 'Red'}
{'Black', 'Red', 'wicket', 'bat', 'ball', 'Blue', 'orange'}


***Dictanories***

In [ ]:
Dict1={"Name":"Kaushik",
       "Age":"30",
       "Gender":"Male"}
  print(Dict1)

IndentationError: ignored

***conditional Statements***

In [ ]:
a=input("enter the value of a");
b=input("enter the value of b");
print(a)
print(b)
if a>b:
  print("value of a is greater than b");

else:
  print("value of b is greater than a");

enter the value of a30
enter the value of b10
30
10
value of a is greater than b


***elif***

In [ ]:
ball1_colour="black"
ball2_colour="blue"
ball3_colour="red"
ball4_colour="green"
pick_ball=input("please pick a ball");
if pick_ball==ball1_colour:
  print("Black ball is picked")
elif pick_ball==ball2_colour:
   print("Blue ball is picked")
elif pick_ball==ball3_colour:
   print("red ball is picked")
else:
   print("Green ball is picked")

please pick a ballred
red ball is picked


**Operators**

**1. Arithmatic operators**

In [ ]:
x=10
y=5
sum=x+y
diff=x-y
prod=x*y
div=x/y
fdiv=x//y
mod=x%y
pow=x**y
print(sum)
print(diff)
print(prod)
print(div)
print(fdiv)
print(mod)
print(pow)

15
5
50
2.0
2
0
100000


***2. Logic operators***

In [ ]:
age=int(input("Enter the age"))
print(type(age))
print(age>18 and age<60)
print(age>18 or age<21)

Enter the age25
<class 'int'>
True
True


***Bitwise operators***

In [ ]:
print(8&12)
print(8|12)
print(8^12)
print(8>>1)
print(12<<1)

8
12
4
4
24


***Assignment Operators***

In [ ]:
a=8
print(a)
a+=3
print(a)
a-=6
print(a)
a*=2
print(a)

8
11
5
10


***Identity and memborship operators***

In [ ]:
x=["Hubli","Dharwad"]
y=["Hubli","Dharwad"]
z=x
z=y
print(z is x)
print(z is y)
print("Dharwad" in x)
print("Hubli" in y)

False
True
True
True


**Looping**
1. While loop

In [ ]:
num=int(input("Enter the number"))
while num<=9:
  print("number is single digit")
  break
while num>9 and num<=99:
  print("number is double digit")
  break
else:
  print("number has more than 2 digits")

Enter the number60
number is double digit


2. For loop

**Basic code**

In [ ]:
for x in range(1,6):
  print(x)
for x in range(1,20,2):
  print(x)


1
2
3
4
5
1
3
5
7
9
11
13
15
17
19


***Factorial***

In [ ]:
fact=1
for num in range(1,6):
  fact*=num
print(fact)

120


***SIngle or Double digit***

In [ ]:
for x in range(5,9):
  print("single digit number")
for x in range(10,99,10):
  print("double digit number")

single digit number
single digit number
single digit number
single digit number
double digit number
double digit number
double digit number
double digit number
double digit number
double digit number
double digit number
double digit number
double digit number


Check the given place is present or not

In [ ]:
places=["Hubli","Dharwad","Haveri","Belagaum"]
for x in places:
  print(x)
  if x=="Haveri":
    print("found")
    break


Hubli
Dharwad
Haveri
found


***Functions***

In [ ]:
def cake_baker():
  print("I am ready to bake")

cake_baker()

I am ready to bake


In [ ]:
def cake_baker(p,f,s):
  print("number of pieces:",p)
  print("flavour:",f)
  print("size:",s)
cake_baker("5","Vanilla","2kg")
cake_baker("20","choclate","3kg")



number of pieces: 5
flavour: Vanilla
size: 2kg
number of pieces: 20
flavour: choclate
size: 3kg


***Args***

In [ ]:
def add(*args):
  sum=0
  for i in args:
    sum+=i
  return sum
print(add(11,20,39,10,59))


139


**Kwargs**

In [ ]:
def greet(**kwargs):
  print("Hello")
  for key,value in kwargs.items():
    print(value,end=" ")
greet(name="Pradhan",usn="01fe21bec098",branch="ECE")

Hello
Pradhan 01fe21bec098 ECE 

***Random***

In [ ]:
import random
x=random.randint(1,9)
print(x)

a=random.random()
print(a)

1
0.7310528795331128


***Game-1***

In [ ]:
import random
comp=random.randint(1,9)
userinput=int(input("Enter the number between 1 to 9"))
print(comp)
print(userinput)
if comp>userinput:
  print("comp won")
elif comp==userinput:
  print("Tie")
else:
  print("you won")

Enter the number between 1 to 95
3
5
you won


***Game-2***

In [ ]:
import random
gamelist=['rock','paper','scissor']
comp=random.choice(gamelist)
user=input("enter either rock or paper or scissor")
print(comp)
print(user)
if(comp=="rock" and user=="scissor" ):
  print("computer won")
elif(comp=="rock" and user=="paper"):
  print("user won")
else:
  print("Tie")

enter either rock or paper or scissorscissor
scissor
scissor
Tie


***Numpy Package***

In [ ]:
import numpy as np
a=np.array([35,1,45,39,20,32,49])
print(type(a))

b=np.zeros(6)
c=np.ones(7)
print(b)
print(c)

d=np.sort(a)
print(d)

<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[ 1 20 32 35 39 45 49]
